### ISSUE TITLE
tritondse - coverage not found- causing triton to never find other seeds 

### ISSUE THREAD

**Issue by hroash** [quarkslab/pastis#11] opened 2024-06-23 15:16 UTC
I'm building your demo file code using:
clang -Wall -g demo.c -o demo.ttt

I'm running the broker with: pastis-broker -b bin -s initial -w output
and than I run tritondse using: pastis-triton online

and I getting warning that coverage wasn't found:
![image](https://github.com/quarkslab/pastis/assets/106006905/7ae2e443-bc12-4725-a059-12841a77c953)

from looking on source code the coverage should be on /mnt/ramdisk or /tmp/triton_{}.trace but it's not on either of them....
This causing triton to never find other seeds 

![image](https://github.com/quarkslab/pastis/assets/106006905/5dcde7d7-0b5c-4e4d-a936-45049a832507)
![image](https://github.com/quarkslab/pastis/assets/106006905/309a3fd1-4c20-446c-8694-be8360d16cea)

**Comment by cnheitman** [comment] 2024-07-05 16:08
Hi! I just tried again the demo, following the step you mentioned and I couldn't reproduce your issue (I tried on a fresh virtual environment, with just pastis installed). 

Could you attach the entire log (for the `pastis-broker` and `pastis-triton`) so I can take a better look at what's going on? Additionally, what version of PyQBDI do you have installed on your system?

**Comment by hroash** [comment] 2024-07-07 07:23
![image](https://github.com/quarkslab/pastis/assets/106006905/5d635e09-d904-4d8f-af32-8a0cebfe289e)
logs:
on the demo/output/logs there are 2 logs but they are empty.

but I had the broker.log:
2024-06-23 16:10:37,389 [[7m[39m[ BROKER ][0m] [INFO]: new binary detected [LINUX, X86_64]: bin/demo.elf
2024-06-23 16:10:37,390 [[7m[39m[ BROKER ][0m] [INFO]: new binary detected [LINUX, X86_64]: bin/demo.ttt
2024-06-23 16:10:37,390 [[7m[39m[ BROKER ][0m] [INFO]: Add seed 1.txt in pool
2024-06-23 16:10:37,391 [[7m[39m[ BROKER ][0m] [INFO]: start broking
2024-06-23 16:10:37,441 [[7m[39m[ BROKER ][0m] [INFO]: [83ab42b6ee7a-0-N-A] [HELLO] Name:83ab42b6ee7a Arch:X86_64 engines:['TRITON'] (cpu:16, mem:33446727680)
2024-06-23 16:10:37,443 [[7m[39m[ BROKER ][0m] [INFO]: send start client 83ab42b6ee7a-0-N-A: demo.ttt [TRITON, EDGE, BINARY_ONLY, SINGLE_EXEC]
2024-06-23 16:11:37,436 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:12:37,478 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:13:37,515 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:14:37,554 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.70%
2024-06-23 16:15:37,597 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.70%
2024-06-23 16:16:37,601 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:17:37,637 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:18:37,639 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:19:37,671 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:20:37,702 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:21:37,733 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:22:37,766 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:23:37,787 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:24:37,823 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:25:37,858 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:26:37,891 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:27:37,927 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:28:37,963 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:29:37,997 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.70%
2024-06-23 16:30:38,030 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:31:38,044 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:32:38,076 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:33:38,114 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:34:38,151 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:35:38,186 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:36:38,221 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:37:38,255 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:38:38,291 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:39:38,327 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:40:38,364 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:41:38,401 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:42:38,436 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:43:38,470 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:44:38,506 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.70%
2024-06-23 16:45:38,547 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:46:38,586 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:47:38,619 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:48:38,650 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:49:38,682 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:50:38,685 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.70%
2024-06-23 16:51:38,695 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:52:38,704 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:53:38,747 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:54:38,795 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:55:38,844 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.80%
2024-06-23 16:56:38,883 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 16:57:38,914 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 16:58:38,956 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 16:59:39,002 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:00:39,031 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:01:39,064 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:02:39,097 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:03:39,130 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:04:39,163 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:05:39,206 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:06:39,241 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:07:39,281 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:08:39,285 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:09:39,323 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:10:39,338 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.30%
2024-06-23 17:11:39,354 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:12:39,369 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:13:39,405 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:14:39,437 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:15:39,471 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:16:39,505 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:17:39,545 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:18:39,579 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:19:39,613 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:20:39,661 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:21:39,668 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:22:39,684 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:23:39,729 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:24:39,743 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:25:39,757 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.40%
2024-06-23 17:26:39,763 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 10.60%
2024-06-23 17:27:39,765 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:28:39,797 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:29:39,834 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:30:39,874 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:31:39,901 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:32:39,938 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:33:39,975 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:34:39,993 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:35:40,031 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:36:40,070 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:37:40,112 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:38:40,149 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:39:40,188 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:40:40,218 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:41:40,227 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:42:40,267 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:43:40,309 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:44:40,310 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:45:40,356 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:46:40,363 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:47:40,376 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:48:40,389 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:49:40,403 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:50:40,418 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:51:40,433 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:52:40,447 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.10%
2024-06-23 17:53:40,448 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.40%
2024-06-23 17:54:40,488 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 11.40%
2024-06-23 17:55:40,492 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.80%
2024-06-23 17:56:40,516 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.10%
2024-06-23 17:57:40,539 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.10%
2024-06-23 17:58:40,570 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.10%
2024-06-23 17:59:40,608 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.20%
2024-06-23 18:00:40,636 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.10%
2024-06-23 18:01:40,670 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.20%
2024-06-23 18:02:40,705 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.70%
2024-06-23 18:03:40,746 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.70%
2024-06-23 18:04:40,780 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 18:05:40,814 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:06:40,844 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.60%
2024-06-23 18:07:40,870 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:08:40,905 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.90%
2024-06-23 18:09:40,938 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.90%
2024-06-23 18:10:40,979 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:11:41,014 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 18:12:41,048 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:13:41,082 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.40%
2024-06-23 18:14:41,110 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.30%
2024-06-23 18:15:41,154 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.20%
2024-06-23 18:16:41,168 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:17:41,179 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:18:41,220 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:19:41,250 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.30%
2024-06-23 18:20:41,264 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.40%
2024-06-23 18:21:41,289 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.10%
2024-06-23 18:22:41,317 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.40%
2024-06-23 18:23:41,365 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.60%
2024-06-23 18:24:41,392 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.60%
2024-06-23 18:25:41,402 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.50%
2024-06-23 18:26:41,425 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.50%
2024-06-23 18:27:41,439 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.70%
2024-06-23 18:28:41,441 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:29:41,483 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:30:41,488 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:31:41,525 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:32:41,545 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:33:41,563 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.90%
2024-06-23 18:34:41,589 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.90%
2024-06-23 18:35:41,623 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.10%
2024-06-23 18:36:41,664 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.10%
2024-06-23 18:37:41,693 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.10%
2024-06-23 18:38:41,734 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.20%
2024-06-23 18:39:41,767 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.10%
2024-06-23 18:40:41,800 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.20%
2024-06-23 18:41:41,816 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.20%
2024-06-23 18:42:41,862 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 15.10%
2024-06-23 18:43:41,862 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.70%
2024-06-23 18:44:41,871 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.80%
2024-06-23 18:45:41,903 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.00%
2024-06-23 18:46:41,937 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.00%
2024-06-23 18:47:41,943 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 14.10%
2024-06-23 18:48:41,985 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.40%
2024-06-23 18:49:42,026 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.40%
2024-06-23 18:50:42,064 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.40%
2024-06-23 18:51:42,095 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:52:42,132 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:53:42,158 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:54:42,191 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:55:42,225 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:56:42,245 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.90%
2024-06-23 18:57:42,268 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 12.30%
2024-06-23 18:58:42,300 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.70%
2024-06-23 18:59:42,327 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.70%
2024-06-23 19:00:42,368 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 19:01:42,385 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 19:02:42,402 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 19:03:42,449 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 13.80%
2024-06-23 19:04:33,154 [[7m[39m[ BROKER ][0m] [INFO]: stop required (Ctrl+C)
2024-06-23 19:04:33,162 [[7m[39m[ BROKER ][0m] [INFO]: Send stop to 83ab42b6ee7a-0-TT
2024-07-07 09:04:06,220 [[7m[39m[ BROKER ][0m] [INFO]: new binary detected [LINUX, X86_64]: bin/demo.elf
2024-07-07 09:04:06,221 [[7m[39m[ BROKER ][0m] [INFO]: new binary detected [LINUX, X86_64]: bin/demo.ttt
2024-07-07 09:04:06,221 [[7m[39m[ BROKER ][0m] [INFO]: Add seed 1.txt in pool
2024-07-07 09:04:06,222 [[7m[39m[ BROKER ][0m] [INFO]: start broking
2024-07-07 09:05:06,232 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 8.90%
2024-07-07 09:05:36,836 [[7m[39m[ BROKER ][0m] [INFO]: [3fef51e4d967-0-N-A] [HELLO] Name:3fef51e4d967 Arch:X86_64 engines:['TRITON'] (cpu:16, mem:33446731776)
2024-07-07 09:05:36,838 [[7m[39m[ BROKER ][0m] [INFO]: send start client 3fef51e4d967-0-N-A: demo.ttt [TRITON, EDGE, BINARY_ONLY, SINGLE_EXEC]
2024-07-07 09:06:06,235 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.50%
2024-07-07 09:07:06,247 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:08:06,291 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:09:06,330 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:10:06,373 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:11:06,382 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:12:06,393 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:13:06,407 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:14:06,415 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.50%
2024-07-07 09:15:06,455 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:16:06,488 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:17:06,530 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:18:06,570 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:19:06,604 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.50%
2024-07-07 09:20:06,648 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:21:06,695 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:22:06,745 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:23:06,749 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.50%
2024-07-07 09:24:06,785 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:25:06,791 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:26:06,832 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%
2024-07-07 09:27:06,879 [[7m[39m[ BROKER ][0m] [DEBUG]: RAM usage: 9.60%

**Comment by RobinDavid** [comment] 2024-07-07 07:38
Hi @hroash.

Logs you sent are not much of any help.

I don't know the exact origin of your problem, but yes its very likely QBDI that does not manage to run on your host.

I suggest that you try running qbdi on your target with an input "by hand" to make sure it generates a coverage file. If it does it will work within pastis.

You can try running this module which also runs as a script: https://github.com/quarkslab/tritondse/blob/main/tritondse/trace.py

(You will just need to modify the code to provide the ``stdin_file`` argument to the ``QBDITrace.run()`` method.

**Comment by hroash** [comment] 2024-07-07 08:15
ok, found the issue, I had python3 and not python so the command is failing:
![image](https://github.com/quarkslab/pastis/assets/106006905/bf7bebc3-d43b-4fc6-a69f-8d84d963e027)
when changing it to python3, it's working

**Comment by RobinDavid** [comment] 2024-07-07 12:30
Interesting. Maybe we shall put python3 for those who don't have an alias from python to python3.

**Comment by cnheitman** [comment] 2024-07-08 16:59
Nice catch! I pushed a fix for this quarkslab/tritondse@bc43b41.

Thanks for reporting!

**Closed as completed by cnheitman** 2024-07-08 16:59 UTC
